<?php

namespace App\Console\Commands;

use Illuminate\Support\Str;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use App\Services\TypeScriptTypeMapper;

class GenerateTypeScript extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'ts:generate
                            {--feature= : Generate types for a specific feature}
                            {--output=resources/ts : The output directory}
                            {--single : Output all types into a single api.ts file}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate TypeScript interfaces from Laravel FormRequests, Resources, and Models';

    protected $mapper;

    public function __construct(TypeScriptTypeMapper $mapper)
    {
        parent::__construct();
        $this->mapper = $mapper;
    }

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $featureFilter = $this->option('feature');
        $outputDir = base_path($this->option('output'));
        $singleFile = $this->option('single');

        if (! File::exists($outputDir)) {
            File::makeDirectory($outputDir, 0755, true);
        }

        $features = [];

        // 1. Process Requests
        $requestFiles = File::allFiles(app_path('Http/Requests'));
        foreach ($requestFiles as $file) {
            $relativePath = $file->getRelativePath();
            if (empty($relativePath)) {
                continue;
            }

            $feature = Str::snake($relativePath);
            if ($featureFilter && $feature !== Str::snake($featureFilter)) {
                continue;
            }

            $class = 'App\\Http\\Requests\\' . str_replace('/', '\\', $relativePath) . '\\' . $file->getBasename('.php');
            $features[$feature]['requests'][] = $class;
        }

        // 2. Process Resources
        $resourceFiles = File::allFiles(app_path('Http/Resources'));
        foreach ($resourceFiles as $file) {
            $relativePath = $file->getRelativePath();
            if (empty($relativePath)) {
                continue;
            }

            $feature = Str::snake($relativePath);
            if ($featureFilter && $feature !== Str::snake($featureFilter)) {
                continue;
            }

            $class = 'App\\Http\\Resources\\' . str_replace('/', '\\', $relativePath) . '\\' . $file->getBasename('.php');
            $features[$feature]['resources'][] = $class;
        }

        // 3. Process Models
        $modelFiles = File::allFiles(app_path('Models'));
        foreach ($modelFiles as $file) {
            $feature = Str::snake($file->getBasename('.php'));
            if ($featureFilter && $feature !== Str::snake($featureFilter)) {
                continue;
            }

            $class = 'App\\Models\\' . str_replace('/', '\\', $file->getRelativePath()) . ($file->getRelativePath() ? '\\' : '') . $file->getBasename('.php');
            $features[$feature]['models'][] = $class;
        }

        $consolidatedContent = "/**\n * Generated by TypeScript Generator - Consolidated\n */\n\n";
        $indexContent = "/**\n * Generated by TypeScript Generator - Index\n */\n\n";

        foreach ($features as $name => $classes) {
            $content = "/**\n * Feature: " . Str::headline($name) . "\n */\n\n";

            $sections = [
                'MODELS' => $classes['models'] ?? [],
                'REQUESTS' => $classes['requests'] ?? [],
                'RESPONSES' => $classes['resources'] ?? [],
            ];

            foreach ($sections as $sectionName => $classList) {
                if (empty($classList)) {
                    continue;
                }

                $content .= "/** --- $sectionName --- **/\n";
                foreach ($classList as $class) {
                    $tsCode = match ($sectionName) {
                        'MODELS' => $this->mapper->mapModel($class),
                        'REQUESTS' => $this->mapper->mapRequest($class),
                        'RESPONSES' => $this->mapper->mapResource($class),
                    };
                    $content .= $tsCode . "\n\n";
                }
            }

            if (! $singleFile) {
                $outputPath = "$outputDir/$name.ts";
                File::put($outputPath, trim($content) . "\n");
                $this->info("Generated: $outputPath");
                $indexContent .= "export * from './$name';\n";
            } else {
                $consolidatedContent .= $content . "\n";
            }
        }

        if ($singleFile) {
            $outputPath = "$outputDir/api.ts";
            File::put($outputPath, trim($consolidatedContent) . "\n");
            $this->info("Generated: $outputPath");
            $indexContent = "export * from './api';\n";
        }

        File::put("$outputDir/index.ts", trim($indexContent) . "\n");
        $this->info("Generated: $outputDir/index.ts");

        $this->info('TypeScript generation complete!');
    }
}
