// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://laravel-boilerplate.test/api/admin' | (string & {});
};

export type ChangeStatus = {
    status: 'active' | 'inactive';
};

export type Media = {
    id: number;
    disk: string;
    directory: string;
    filename: string;
    extension: string;
    mime_type: string;
    aggregate_type: string;
    size: number;
    url: string;
    cdn_url: string | null;
};

export type Setting = {
    id: number;
    key: string;
    value: string;
    collection: string | null;
    is_public: number;
    updated_by: number | null;
};

export type User = {
    id: number;
    first_name: string | null;
    last_name: string | null;
    name: string;
    username: string | null;
    email: string;
    status: UserStatus;
    display_status: string;
    country_code: string | null;
    mobile_no: string | null;
    display_mobile_no: string;
    email_verified_at: number | null;
    last_login_at: number;
    created_at: number | null;
    profile_image?: Media;
    user_device?: UserDevice;
};

export type UserDevice = {
    id: number;
    user_id: number | null;
    onesignal_player_id: string | null;
    device_id: string | null;
    device_type: string | null;
};

export const UserStatus = { ACTIVE: 'active', INACTIVE: 'inactive' } as const;

export type UserStatus = typeof UserStatus[keyof typeof UserStatus];

export type AdminUserStatusData = {
    body: ChangeStatus;
    path: {
        user: number;
    };
    query?: never;
    url: '/users/{user}/change-status';
};

export type AdminUserStatusErrors = {
    401: {
        message: string;
    };
    404: {
        message: string;
    };
    422: {
        message: string;
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type AdminUserStatusError = AdminUserStatusErrors[keyof AdminUserStatusErrors];

export type AdminUserStatusResponses = {
    200: {
        message: string;
        user: User;
    };
};

export type AdminUserStatusResponse = AdminUserStatusResponses[keyof AdminUserStatusResponses];

export type SettingIndexData = {
    body?: never;
    path?: never;
    query?: {
        sort?: string;
        include?: string;
        'filter[key]'?: string;
        'filter[value]'?: string;
        'filter[collection]'?: string;
        'filter[is_public]'?: string;
        'filter[updated_by]'?: string;
    };
    url: '/settings';
};

export type SettingIndexErrors = {
    401: {
        message: string;
    };
};

export type SettingIndexError = SettingIndexErrors[keyof SettingIndexErrors];

export type SettingIndexResponses = {
    200: {
        data: Array<Setting>;
    };
};

export type SettingIndexResponse = SettingIndexResponses[keyof SettingIndexResponses];

export type SettingUpdateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings';
};

export type SettingUpdateErrors = {
    401: {
        message: string;
    };
    422: {
        message: string;
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type SettingUpdateError = SettingUpdateErrors[keyof SettingUpdateErrors];

export type SettingUpdateResponses = {
    200: {
        message: string;
    };
};

export type SettingUpdateResponse = SettingUpdateResponses[keyof SettingUpdateResponses];
