#!/bin/sh

# Run Laravel Pint
# This script will run Laravel Pint on newly staged PHP Files. 

files=$(git diff --cached --name-only --diff-filter=AMCR | grep "\.php$")
if echo "$files" | grep --quiet "\.php$"; then
 echo "Running Laravel Pint..."
 ./vendor/bin/pint $files && git add $files
fi

# Check if Duster fix is needed
if [ ! -f .duster.lock ]; then
    # Run Duster fix
    ./vendor/bin/duster fix

    # Check if Duster fix failed
    if [ $? -ne 0 ]; then
        echo "Duster fix failed. Aborting commit."
        exit 1
    fi

    # Create lock file to indicate Duster fix has been run
    touch .duster.lock

    # If Duster fix succeeded, commit the code
    git add .
    git commit -m "Auto-commit after successful Duster fix"
fi