#!/bin/sh

# Run Laravel Pint
# This script will run Laravel Pint on newly staged PHP Files. 

# Check if Duster fix is needed
if [ ! -f .duster.lock ]; then
    # Run Duster fix
    ./vendor/bin/duster fix

    # Check if Duster fix failed
    if [ $? -ne 0 ]; then
        echo "Duster fix failed. Aborting commit."
        exit 1
    fi

    # If Duster fix succeeded, commit the code
    git add .
    git commit -m "Auto-commit after successful Duster fix"

    # Remove lock file after successful commit
    rm .duster.lock
fi